In [1]:
import sys
print(f"Python version: {sys.version}")

import platform
print(f"Platform: {platform.platform()}")
import numpy as np
print(f"Numpy version: {np.__version__}")
import scipy
print(f"SciPy version: {scipy.__version__}")
import matplotlib
print(f"Matplotlib version: {matplotlib.__version__}")
import pandas as pd
print(f"Pandas version: {pd.__version__}")
import sklearn
print(f"Scikit-learn version: {sklearn.__version__}")
import IPython
print(f"IPython version: {IPython.__version__}")

Python version: 3.11.14 (main, Oct 28 2025, 12:11:26) [Clang 20.1.4 ]
Platform: Linux-6.14.0-35-generic-x86_64-with-glibc2.41
Numpy version: 2.3.2
SciPy version: 1.16.3
Matplotlib version: 3.10.7
Pandas version: 2.3.1
Scikit-learn version: 1.7.2
IPython version: 9.7.0


In [3]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()
print(f"Iris dataset keys: {iris_dataset.keys()}")
print(f"Iris target names: {iris_dataset['target_names']}")
print(f"Iris feature names: {iris_dataset['feature_names']}")
print(f"Iris data shape: {iris_dataset['data'].shape}")
print(f"Iris first five rows of data:\n{iris_dataset['data'][:5]}")

Iris dataset keys: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
Iris target names: ['setosa' 'versicolor' 'virginica']
Iris feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Iris data shape: (150, 4)
Iris first five rows of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
